### ISSUE TITLE
Enable support for multi-line comments 

### ISSUE THREAD

**Issue by mainak55512** [mainak55512/stto#2]
Currently stto supports single line comments for the supported languages. Need to enable multi-line comments and do the adjustments needed.

**Comment by yogesh19k** [comment]
I can take this @mainak55512 please assign this to me

**Comment by mainak55512** [comment]
> I can take this @mainak55512 please assign this to me

Done

**Comment by yogesh19k** [comment]
@mainak55512 created a pull request

**Comment by yogesh19k** [comment]
Please close this issue as it has been added using #6
